### ISSUE TITLE
A connection to the deployment share could not be made

### ISSUE THREAD

**Issue by raandree** [GlennJC/AL-Scripts#7]
I have tested the MDT part today. Great job!

After some minor tweaks that I will share later, the MDT server was ready to use. A new VM connected to the network could talk to the MDT server but then this error appeared:

![image](https://user-images.githubusercontent.com/11280760/34449657-fc2998a2-ecfa-11e7-894a-48b814949e41.png)

I have checked the bootstrap.ini, credentials are fine. Name resolution works and from the cmd on the client I can successfully access the DeploymentShare.

Do you have an idea what I am doing wrong?

**Comment by GlennJC** [comment]
Thanks :)

@raandree, haven't seen that error before except where there was a DC is the mix and the local install account defined in the bootstrap.ini didn't have the required permissions set up. Have seen a similar issue with Creator / Owner still applied on the root of the volume, and the installation account owns all the files at the exclusion of other users .  I'll have a dig into this over the weekend.

**Comment by GlennJC** [comment]
@raandree. Think I may have found the issue with this one, is definitely a bug.  

The Install-MDT cmdlet takes an account name and password for to write to the bootstrap.ini file, but does no checking to see if they are valid.  The default behavior in the script is to user 'Administrator' 'Somepass1' (which is an assumption on the default credentials used by AutomatedLab).

Have made some changes to use the credentials within the Lab Definition itself, rather than rely on the script providing the correct credentials.  Currently testing, will provide an updated script shortly.

**Comment by GlennJC** [comment]
@raandree believe issue is now fixed, can you rested if possible?

**Comment by raandree** [comment]
Everything now runs as expected, thanks!
